services:

  postgres:
    image: postgres:16
    container_name: favorite_places_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - favorite_places_network


  server:
    build:
      context: ./server
    container_name: favorite_places_server
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: supersecret
      DB_NAME: postgres
    ports:
      - "3000:3000"
    networks:
      - favorite_places_network

  client:
    build:
      context: ./client
    container_name: favorite_places_client
    restart: always
    depends_on:
      - server
    ports:
      - "5173:80"
    networks:
      - favorite_places_network

volumes:
  postgres_data:

networks:
  favorite_places_network:
    driver: bridge