services:
  manager:
    image: docker:dind
    container_name: manager
    privileged: true

  node1:
    image: docker:dind
    container_name: node1
    privileged: true

  node2:
    image: docker:dind
    container_name: node2
    privileged: true