[managers]
# it should be the docker container name of the manager node, in our case "manager" prefixed by docker compose
manager-1

[managers:vars]
ansible_connection=community.docker.docker

[workers]
# it should be the docker container name of the worker nodes, in our case "node" prefixed by docker compose
node-1
node-2
node-3
node-4

[workers:vars]
ansible_connection=community.docker.docker