[managers]
# it should be the docker container name of the manager node, in our case "manager" prefixed by docker compose
infra-manager-1

[managers:vars]
ansible_connection=community.docker.docker
ansible_python_interpreter=/usr/bin/python3
ansible_shell_executable=/bin/sh
ansible_remote_tmp=/tmp

[workers]
# it should be the docker container name of the worker nodes, in our case "node" prefixed by docker compose
infra-node-1
infra-node-2
infra-node-3

[workers:vars]
ansible_connection=community.docker.docker
ansible_python_interpreter=/usr/bin/python3
ansible_shell_executable=/bin/sh
ansible_remote_tmp=/tmp